### ISSUE TITLE
'nullptr' not defined in this scope due to missing g++ -std=c++0x parameter

### ISSUE THREAD

**Issue by Dantali0n** [fralonra/Zrandr#1]
Using qt5 its qmake on the zrandr.pro file results in a makefile without the -std=c++0x parameter. This causes the compilation to fail since the definition of 'nullptr' will remain undefined.

**Comment by fralonra** [comment]
I added a line `CONFIG += C++11` in the zrandr.pro file, and the build was successful on my old PC ( qmake3.0, Qt 5.3.0). Can it fix your problem?

**Comment by Dantali0n** [comment]
By adding `CONFIG += C++11` to the zrandr.pro file the issue is resolved.
